<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-16T10:29:43 IST" name="Suite" finished-at="2023-08-16T10:30:09 IST" duration-ms="26218">
    <groups>
      <group name="regression">
        <method signature="TC_003_RegistrationTest.test_account_Registration()[pri:0, instance:com.ebankingprpject.TestCases.TC_003_RegistrationTest@3f191845]" name="test_account_Registration" class="com.ebankingprpject.TestCases.TC_003_RegistrationTest"/>
      </group> <!-- regression -->
      <group name="sanity">
        <method signature="TC_003_RegistrationTest.test_account_Registration()[pri:0, instance:com.ebankingprpject.TestCases.TC_003_RegistrationTest@3f191845]" name="test_account_Registration" class="com.ebankingprpject.TestCases.TC_003_RegistrationTest"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2023-08-16T10:29:43 IST" name="Test" finished-at="2023-08-16T10:30:09 IST" duration-ms="26218">
      <class name="com.ebankingprpject.TestCases.TC_003_RegistrationTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.ebankingprpject.TestCases.TC_003_RegistrationTest@3f191845]" started-at="2023-08-16T10:29:43 IST" name="setup" finished-at="2023-08-16T10:29:50 IST" duration-ms="6477" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test_account_Registration()[pri:0, instance:com.ebankingprpject.TestCases.TC_003_RegistrationTest@3f191845]" started-at="2023-08-16T10:29:50 IST" name="test_account_Registration" finished-at="2023-08-16T10:30:07 IST" duration-ms="17594" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.ebankingprpject.TestCases.TC_003_RegistrationTest.test_account_Registration(TC_003_RegistrationTest.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_account_Registration -->
        <test-method is-config="true" signature="teadDown()[pri:0, instance:com.ebankingprpject.TestCases.TC_003_RegistrationTest@3f191845]" started-at="2023-08-16T10:30:09 IST" name="teadDown" finished-at="2023-08-16T10:30:09 IST" duration-ms="227" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teadDown -->
      </class> <!-- com.ebankingprpject.TestCases.TC_003_RegistrationTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
